version: '3'
services:
  api:
    container_name: api
    image: template_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
      - DATABASE_USERNAME=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
    depends_on:
      - database
  database:
    image: 'postgres:14.1-alpine'
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      # Directory must exist in a file system
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
