#server:
#  port: 80
#  error.include-message: always
#template:
#spring:
#  profiles:
#    active: ${ACTIVE_PROFILE}
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-version: 0
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        dialect: org.hibernate.dialect.H2Dialect
#management:
#  health.enabled: true
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  import: env.properties
#  jpa:
#    show-sql: true
#template:
#
#---
#spring:
#  config:
#    activate:
#      on-profile: qa
#template:
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#template:
server:
  port: 80
  error.include-message: always
spring:
  profiles:
  #  active: ${ACTIVE_PROFILE}
    active: dev
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    #  url: jdbc:postgresql://localhost:5432/postgres
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    #  username: postgres
    #  password: postgres
  jpa:
    hibernate:
    #  ddl-auto: create-drop
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        dialect: org.hibernate.dialect.H2Dialect
management:
  health.enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
