server:
  port: 80
  error.include-message: always
spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    url: jdbc:postgresql://localhost:5432/localdb
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        dialect: org.hibernate.dialect.H2Dialect
management:
  health.enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prod
